title:              SVTCHIVE
email:              ""
description:        ì‹œê°„ê³¼ ê³µê°„ì— êµ¬ì• ë°›ì§€ ì•ŠëŠ” ì„¸ë¸í‹´ ì €ì¥ì†ŒğŸ—‚ï¸
author:             SVTCHIVE
baseurl:            ""
url:                "https://svtchive.kr"
enforce_ssl:        "www.svtchive.kr"

# Social Profiles
twitter_username:   SVTCHIVE
github_username:
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-188229767-1 # out your google-analytics code

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           10
paginate_path:      "/playlists/page:num"
plugins:
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
